# Generated by Django 4.0.3 on 2022-04-24 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_studentprofile_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
