# Generated by Django 4.0.3 on 2022-04-24 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_studentprofile_profile_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
